# Generated by Django 5.2.8 on 2025-11-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=80)),
                ('temperature', models.FloatField()),
                ('humidity', models.PositiveIntegerField()),
                ('pressure', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=120)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
